name: CDK Deploy

on:
  push:
    branches:
      - stable-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout stable-test branch
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or the version you prefer

    - name: Install dependencies
      run: |
        npm install
        npm install -g aws-cdk

    # - name: Run Tests
    #   run: npm test

    - name: CDK Deploy
      run: cdk deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
